[server]
listen_addr = "0.0.0.0"
listen_port = 8890
[store]
path = "/home/tpa/Heimerdinger-Lab/Karma/temp"
[raft]
count = 3
server_id = 3
members = ["127.0.0.1:8888", "127.0.0.1:8889", "127.0.0.1:8890"]


